package biograph.gui;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author noelb
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private biograph.logic.Grafo grafo = new biograph.logic.Grafo();
    private biograph.util.ManejadorArchivos manejador = new biograph.util.ManejadorArchivos();

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        jPanel2 = new biograph.gui.PanelGrafo();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        PanelFondo.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(57, 255, 20));
        jButton1.setText("Cargar CSV");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(57, 255, 20));
        jButton2.setText("Guardar Repositorio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(57, 255, 20));
        jButton3.setText("Buscar Proteina");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(57, 255, 20));
        jButton4.setText("Detectar Complejos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(57, 255, 20));
        jButton5.setText("Ruta mas corta");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(57, 255, 20));
        jButton6.setText("Agregar Conexion");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(57, 255, 20));
        jButton7.setText("Eliminar Proteina");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(71, 71, 71)))
                .addContainerGap())
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6))
                        .addGap(20, 20, 20)
                        .addGroup(PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton3)
                            .addComponent(jButton7)))
                    .addGroup(PanelFondoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// 1. Advertencia requerida por el profesor (Tolerancia a fallos / Usabilidad)
    if (grafo != null && grafo.getVertices().size() > 0) {
        int resp = JOptionPane.showConfirmDialog(this, 
            "Ya hay un grafo en memoria. ¿Desea continuar y sobrescribir los datos actuales no guardados?", 
            "Advertencia de Sobrescritura", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if (resp == JOptionPane.NO_OPTION) {
            return; // Cancela la acción de cargar
        }
    }

    // 2. Abrir el buscador de archivos
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Seleccione el archivo maestro CSV");
    
    int seleccion = fileChooser.showOpenDialog(this);
    if (seleccion == JFileChooser.APPROVE_OPTION) {
        java.io.File archivo = fileChooser.getSelectedFile();
        
        // 3. Reiniciar el grafo y cargar los datos
        grafo = new biograph.logic.Grafo(); 
        manejador.cargarArchivo(archivo, grafo);
        
        // 4. Actualizar la vista gráfica (CAMBIA 'jPanel2' POR EL NOMBRE DE TU PANEL)
        ((biograph.gui.PanelGrafo) jPanel2).actualizarGrafo(grafo); 
    }    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     if (grafo == null || grafo.getVertices().size() == 0) {
        JOptionPane.showMessageDialog(this, "No hay ningún grafo para guardar.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Guardar repositorio como...");
    
    int seleccion = fileChooser.showSaveDialog(this);
    if (seleccion == JFileChooser.APPROVE_OPTION) {
        java.io.File archivo = fileChooser.getSelectedFile();
        manejador.guardarArchivo(archivo, grafo);
    }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if (grafo == null || grafo.getVertices().size() == 0) {
        JOptionPane.showMessageDialog(this, "Primero debe cargar un grafo.");
        return;
    }
    biograph.logic.Vertice hub = grafo.obtenerHub();
    JOptionPane.showMessageDialog(this, 
        "La proteína Hub (con más conexiones) es: " + hub.getNombre() + 
        "\nTotal de conexiones: " + hub.getAdyacencia().size(), 
        "Centralidad de Grado", JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
if (grafo == null || grafo.getVertices().size() == 0) {
        JOptionPane.showMessageDialog(this, "Primero debe cargar un grafo.");
        return;
    }
    biograph.logic.Lista<biograph.logic.Lista<biograph.logic.Vertice>> complejos = grafo.obtenerComplejos();
    StringBuilder mensaje = new StringBuilder("Se encontraron " + complejos.size() + " complejos proteicos:\n\n");
    
    for (int i = 0; i < complejos.size(); i++) {
        mensaje.append("Complejo ").append(i + 1).append(": ");
        biograph.logic.Lista<biograph.logic.Vertice> comp = complejos.get(i);
        for (int j = 0; j < comp.size(); j++) {
            mensaje.append(comp.get(j).getNombre()).append(j < comp.size() - 1 ? ", " : "");
        }
        mensaje.append("\n");
    }
    JOptionPane.showMessageDialog(this, mensaje.toString(), "Resultados DFS", JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
if (grafo == null || grafo.getVertices().size() == 0) {
        JOptionPane.showMessageDialog(this, "Primero debe cargar un grafo.");
        return;
    }
    String origen = JOptionPane.showInputDialog(this, "Ingrese el nombre de la proteína de ORIGEN:");
    if (origen == null || origen.trim().isEmpty()) return;
    
    String destino = JOptionPane.showInputDialog(this, "Ingrese el nombre de la proteína de DESTINO:");
    if (destino == null || destino.trim().isEmpty()) return;

    biograph.logic.Lista<biograph.logic.Vertice> ruta = grafo.dijkstra(origen.trim(), destino.trim());
    
    if (ruta == null) {
        JOptionPane.showMessageDialog(this, "Uno o ambos vértices no existen en el grafo.", "Error", JOptionPane.ERROR_MESSAGE);
    } else if (ruta.size() == 0) {
        JOptionPane.showMessageDialog(this, "No existe una ruta posible entre " + origen + " y " + destino, "Ruta no encontrada", JOptionPane.WARNING_MESSAGE);
    } else {
        StringBuilder mensaje = new StringBuilder("Ruta más corta desde " + origen + " hasta " + destino + ":\n");
        // Leemos la ruta de atrás hacia adelante porque Dijkstra la construye desde el destino
        for (int i = ruta.size() - 1; i >= 0; i--) {
            mensaje.append(ruta.get(i).getNombre());
            if (i > 0) mensaje.append(" -> ");
        }
        JOptionPane.showMessageDialog(this, mensaje.toString(), "Resultado de Dijkstra", JOptionPane.INFORMATION_MESSAGE);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
if (grafo == null) {
        // Si no hay grafo, creamos uno nuevo vacío para empezar a agregar
        grafo = new biograph.logic.Grafo(); 
    }

    String origen = JOptionPane.showInputDialog(this, "Ingrese el nombre de la proteína de ORIGEN:");
    if (origen == null || origen.trim().isEmpty()) return;

    String destino = JOptionPane.showInputDialog(this, "Ingrese el nombre de la proteína de DESTINO:");
    if (destino == null || destino.trim().isEmpty()) return;

    String pesoStr = JOptionPane.showInputDialog(this, "Ingrese el costo de la interacción (número):");
    if (pesoStr == null || pesoStr.trim().isEmpty()) return;

    try {
        int peso = Integer.parseInt(pesoStr.trim());
        
        // Insertamos la arista (esto crea los vértices automáticamente si no existen)
        grafo.insertarArista(origen.trim(), destino.trim(), peso);
        
        // Actualizamos la vista gráfica (CAMBIA 'jPanel2' POR EL NOMBRE DE TU PANEL)
        ((biograph.gui.PanelGrafo) jPanel2).actualizarGrafo(grafo); 
        
        JOptionPane.showMessageDialog(this, "Conexión agregada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "El costo (peso) debe ser un número entero válido.", "Error", JOptionPane.ERROR_MESSAGE);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
   if (grafo == null || grafo.getVertices().size() == 0) {
        JOptionPane.showMessageDialog(this, "No hay ningún grafo en memoria para modificar.", "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre de la proteína que desea ELIMINAR:");
    if (nombre != null && !nombre.trim().isEmpty()) {
        
        // Verificamos si existe antes de intentar eliminar
        biograph.logic.Vertice v = grafo.buscarVertice(nombre.trim());
        
        if (v != null) {
            grafo.eliminarVertice(nombre.trim());
            
            // Actualizamos la vista gráfica (CAMBIA 'jPanel2' POR EL NOMBRE DE TU PANEL)
            ((biograph.gui.PanelGrafo) jPanel2).actualizarGrafo(grafo); 
            
            JOptionPane.showMessageDialog(this, "Proteína '" + nombre + "' y todas sus conexiones han sido eliminadas.", "Eliminado", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "La proteína '" + nombre + "' no existe en el grafo.", "No encontrada", JOptionPane.ERROR_MESSAGE);
        }
    }     // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
